apiVersion: v1
kind: Pod
metadata:
  name: kubedebug
  namespace: tst
spec:
  serviceAccountName: default
  containers:
    - name: kubedebug
      image: docker.io/pavedroad/kubedubug
      env:
      - name: LIFETIME
        value: "86400"
